version: '2'
services:
    server:
        container_name: servidor
        restart: always
        build: ./server
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app/back
            - /usr/app/back/node_modules       
        