
name: Integracion Continua



# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-server: 
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Intalacion Depencias
        run: |
          cd server
          sudo npm i --save-dev typescript	
          sudo npm install

  deploy-server:
      
    runs-on: self-hosted
    needs: build-server
    env: # Or as an environment variable
      USER: ${{ secrets.DOCKER_USER }}
      PASS: ${{ secrets.DOCKER_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker logs
        run: docker login -u mdmata -p 9adabc6a-1e46-4198-8687-f2037eb1349a
       
      - name: Tags
        run: |
          docker tag back mdmata/back:${{ github.sha }}
          docker tag back mdmata/back:latest
      - name: push
        run: |
          docker push mdmata/back:${{ github.sha }}
          docker push mdmata/back:latest
      - name: Build
        run: docker-compose -f "docker-compose.yml" up -d --build

  build-cliente:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Intalacion Depencias
        run: |
          cd Frontend
          cd Proyecto
          sudo npm install
          docker login -u mdmata -p 9adabc6a-1e46-4198-8687-f2037eb1349a
          docker build --no-cache -t "mdmata/cliente_app:latest" ./
          docker push "mdmata/cliente_app:latest"

  deploy-cliente:

    runs-on: self-hosted

    steps:
      
      - uses: actions/checkout@v2
      - name: stops
        run: |
          docker stop cliente_app
          docker rm cliente_app
      - name: run
        run: |
          docker login -u mdmata -p 9adabc6a-1e46-4198-8687-f2037eb1349a
          docker pull "mdmata/cliente_app:latest"
          docker run -d -p 0.0.0.0:80:4200 -name=cliente mdmata/cliente_app:latest
          docker image prune
          docker logout





