# This is a basic workflow to help you get started with Actions

name: Integracion Continua

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [14.15.4]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Intalacion Depencias
        run: |
          cd server
          npm install
          npm build
      - name: npm run dev
        run: |
          cd server
          npm cache clean --force
          npm install
          npm run dev
      - name: Test
        run: |
          cd server
          npm test

  
    
