
name: Integracion Continua



# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  build-cliente:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Intalacion Depencias
        run: |
          cd Frontend
          cd Proyecto
          docker login -u mdmata -p 9adabc6a-1e46-4198-8687-f2037eb1349a
          docker build --no-cache -t "mdmata/front:latest" ./
          docker push mdmata/front:latest"

  deploy-cliente:

    runs-on: self-hosted
    needs: build-cliente
    
    environment:
      name: production
      url: http://35.188.63.171:4200/
    
    steps:

      - uses: actions/checkout@v2
      - name: Docker logs
        run: docker login -u mdmata -p 9adabc6a-1e46-4198-8687-f2037eb1349a

      - name: push
        run: |
          docker pull "mdmata/front:latest"
          docker run -d -p 0.0.0.0:4200:4200 --name=server mdmata/front:latest
          docker logout